% Basic class for 6.4110 homework
%
%
\NeedsTeXFormat{LaTeX2e}[1995/12/01]
\ProvidesClass{64110}
              [2011/02/01 - v1.0
 Standard class for 6.4110 homework]

\LoadClass[12pt]{article}
\RequirePackage{64110}

\typeout{}
\typeout{*** Document Class '64110 for 6.4110 homework}
\typeout{*** Adapted from 6.1220 homework}
\typeout{*** Bugs/comments/suggestions/technicalities via 6.1220 Piazza.}
\typeout{}
